# Generated by Django 4.0 on 2021-03-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0003_alter_driver_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(default='test@test.com', max_length=25),
        ),
    ]
