# Generated by Django 4.0 on 2021-03-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_app', '0003_auto_20210219_0349'),
        ('driver_app', '0004_driver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='sponsor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor_app.sponsor'),
        ),
    ]
