# Generated by Django 4.0 on 2021-03-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0005_alter_driver_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
