# Generated by Django 4.0 on 2021-02-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=20)),
                ('exchange_rate', models.IntegerField(default=1)),
                ('catalog', models.CharField(max_length=100)),
                ('catalog_key', models.CharField(max_length=100)),
            ],
        ),
    ]
