# Generated by Django 4.0 on 2021-02-19 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsor_app', '0002_sponsor_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='account_id',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
