# Generated by Django 3.1.6 on 2021-04-02 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_app', '0003_auto_20210219_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='application_requirements',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
