# Generated by Django 3.1.6 on 2021-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_app', '0003_auto_20210219_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='application_requirements',
            field=models.CharField(default='none', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
